// require("dotenv").config();
import dotenv from "dotenv";
dotenv.config();
import request from "request";
import chatBotService from "../services/chatBotService.js";
import { GoogleSpreadsheet } from "google-spreadsheet";

const PAGE_ACCESS_TOKEN = process.env.PAGE_ACCESS_TOKEN;
const SPREADSHEET_ID = process.env.SPREADSHEET_ID;
const GOOGLE_SERVICE_ACCOUNT_EMAIL = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
const GOOGLE_PRIVATE_KEY = process.env.GOOGLE_PRIVATE_KEY;

let writeDataToGoogleSheet = async (data) => {
  let currentDate = new Date();
  const format = "HH:mm DD/MM/YYYY";
  let formattedDate = moment(currentDate).format(format);

  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet(SPREADSHEET_ID);

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: JSON.parse(`"${GOOGLE_SERVICE_ACCOUNT_EMAIL}"`),
    private_key: JSON.parse(`"${GOOGLE_PRIVATE_KEY}"`),
  });

  await doc.loadInfo(); // loads document properties and worksheets

  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]

  // append rows
  await sheet.addRow({
    "Tên Facebook": data.username,
    "Địa chỉ Email": data.email,
    "Số điện thoại": data.phoneNumber,
    "Thời gian": formattedDate,
    "Tên khách hàng": data.customerName,
  });
};

let postWebhook = (req, res) => {
  // Parse the request body from the POST
  let body = req.body;

  // Check the webhook event is from a Page subscription
  if (body.object === "page") {
    // Iterate over each entry - there may be multiple if batched
    body.entry.forEach(function (entry) {
      // Gets the body of the webhook event
      let webhook_event = entry.messaging[0];
      console.log(webhook_event);

      // Get the sender PSID
      let sender_psid = webhook_event.sender.id;
      console.log("Sender PSID: " + sender_psid);

      // Check if the event is a message or postback and
      // pass the event to the appropriate handler function
      if (webhook_event.message) {
        handleMessage(sender_psid, webhook_event.message);
      } else if (webhook_event.postback) {
        handlePostback(sender_psid, webhook_event.postback);
      }
    });

    // Return a '200 OK' response to all events
    res.status(200).send("EVENT_RECEIVED");
  } else {
    // Return a '404 Not Found' if event is not from a page subscription
    res.sendStatus(404);
  }
};

let getWebhook = (req, res) => {
  // Your verify token. Should be a random string.
  let VERIFY_TOKEN = process.env.VERIFY_TOKEN;

  // Parse the query params
  let mode = req.query["hub.mode"];
  let token = req.query["hub.verify_token"];
  let challenge = req.query["hub.challenge"];

  // Checks if a token and mode is in the query string of the request
  if (mode && token) {
    // Checks the mode and token sent is correct
    if (mode === "subscribe" && token === VERIFY_TOKEN) {
      // Responds with the challenge token from the request
      console.log("WEBHOOK_VERIFIED");
      res.status(200).send(challenge);
    } else {
      // Responds with '403 Forbidden' if verify tokens do not match
      res.sendStatus(403);
    }
  }
};

// Handles messages events
function handleMessage(sender_psid, received_message) {
  let response;

  // Checks if the message contains text
  if (received_message.text) {
    // Create the payload for a basic text message, which
    // will be added to the body of our request to the Send API
    response = {
      text: `You sent the message: "${received_message.text}". Now send me an attachment!`,
    };
  } else if (received_message.attachments) {
    // Get the URL of the message attachment
    let attachment_url = received_message.attachments[0].payload.url;
    response = {
      attachment: {
        type: "template",
        payload: {
          template_type: "generic",
          elements: [
            {
              title: "Is this the right picture?",
              subtitle: "Tap a button to answer.",
              image_url: attachment_url,
              buttons: [
                {
                  type: "postback",
                  title: "Yes!",
                  payload: "yes",
                },
                {
                  type: "postback",
                  title: "No!",
                  payload: "no",
                },
              ],
            },
          ],
        },
      },
    };
  }

  // Send the response message
  callSendAPI(sender_psid, response);
}

// Handles messaging_postbacks events
let handlePostback = async (sender_psid, received_postback) => {
  let response;

  // Get the payload for the postback
  let payload = received_postback.payload;

  // Set the response based on the postback payload
  switch (payload) {
    case "yes":
      response = { text: "Thanks!" };
      break;

    case "no":
      response = { text: "Oops, try sending another image." };
      break;

    case "RESTART_CONVERSATION":
    case "GET_STARTED":
      await chatBotService.handleGetStarted(sender_psid);
      break;

    case "MAIN_MENU":
      await chatBotService.sendMainMenu(sender_psid);
      break;
    case "LUNCH_MENU":
      await chatBotService.sendLunchMenu(sender_psid);
      break;
    case "DINNER_MENU":
      await chatBotService.sendDinnerMenu(sender_psid);
      break;

    // Lunch Menu Detail
    case "SHOW_APPETIZERS":
      await chatBotService.sendAppetizer(sender_psid);
      break;
    case "SHOW_FISH":
      await chatBotService.sendFish(sender_psid);
      break;
    case "SHOW_MEAT_BACON":
      await chatBotService.sendMeatBacon(sender_psid);
      break;

    case "BACK_TO_MAIN_MENU":
      await chatBotService.backToMainMenu(sender_psid);
      break;

    case "SHOW_ROOMS":
      await chatBotService.handleShowDetailRoom(sender_psid);
      break;

    default:
      response = {
        text: `Oops! Sorry, I don't know request with postback ${payload}`,
      };
  }

  // Send the message to acknowledge the postback
  callSendAPI(sender_psid, response);
};

// Sends response messages via the Send API
function callSendAPI(sender_psid, response) {
  // Construct the message body
  let request_body = {
    recipient: {
      id: sender_psid,
    },
    message: response,
  };

  // Send the HTTP request to the Messenger Platform
  request(
    {
      uri: "https://graph.facebook.com/v2.6/me/messages",
      qs: { access_token: process.env.PAGE_ACCESS_TOKEN },
      method: "POST",
      json: request_body,
    },
    (err, res, body) => {
      if (!err) {
        console.log("message sent!");
      } else {
        console.error("Unable to send message:" + err);
      }
    }
  );
}

let setupProfile = async (req, res) => {
  // call profile facebook api
  // Construct the message body
  let request_body = {
    get_started: {
      payload: "GET_STARTED",
    },
    whitelisted_domains: ["https://chatbot-fb-messenger-io7a.onrender.com/"],
  };

  // Send the HTTP request to the Messenger Platform
  await request(
    {
      uri: `https://graph.facebook.com/v17.0/me/messenger_profile?access_token=${PAGE_ACCESS_TOKEN}`,
      qs: { access_token: PAGE_ACCESS_TOKEN },
      method: "POST",
      json: request_body,
    },
    (err, res, body) => {
      console.log("body:", body);
      if (!err) {
        console.log("Set up user profile successfully!");
      } else {
        console.error("Unable to set up user profile:" + err);
      }
    }
  );

  return res.send("Set up user profile successfully!");
};

let setupPersistentMenu = async (req, res) => {
  // Construct the message body
  let request_body = {
    persistent_menu: [
      {
        locale: "default",
        composer_input_disabled: false,
        call_to_actions: [
          {
            type: "web_url",
            title: "View Youtube Channel",
            url: "https://www.youtube.com/@VAM.Nguyen",
            webview_height_ratio: "full",
          },
          {
            type: "web_url",
            title: "View Facebook Fan Page",
            url: "https://facebook.com/vamnguyenpage",
            webview_height_ratio: "full",
          },
          {
            type: "postback",
            title: "Restart this conversation",
            payload: "RESTART_CONVERSATION",
          },
        ],
      },
    ],
  };

  // Send the HTTP request to the Messenger Platform
  await request(
    {
      uri: `https://graph.facebook.com/v17.0/me/messenger_profile?access_token=${PAGE_ACCESS_TOKEN}`,
      qs: { access_token: PAGE_ACCESS_TOKEN },
      method: "POST",
      json: request_body,
    },
    (err, res, body) => {
      console.log("body:", body);
      if (!err) {
        console.log("Set up persistent menu successfully!");
      } else {
        console.error("Unable to set up persistent menu:" + err);
      }
    }
  );

  return res.send("Set up persistent menu successfully!");
};

let handleTableReservation = (req, res) => {
  return res.render("tableReservation.ejs");
};

let handlePostReserveTable = async (req, res) => {
  try {
    const username = await chatBotService.getUserName(req.body.psid);

    // write data to google spreadsheet
    let data = {
      username,
      email: req.body.email,
      phoneNumber: `'${req.body.phoneNumber}`,
      customerName: req.body.customerName,
    };
    await writeDataToGoogleSheet(data);

    let customerName = "";
    if (req.body.customerName === "") {
      customerName = username;
    } else customerName = req.body.customerName;

    // I demo response with sample text
    // you can check database for customer order's status

    let response = {
      text: `---Info customer table reservation---
        \nCustomer name: ${customerName}
        \nEmail address: ${req.body.email}
        \nPhone number: ${req.body.phoneNumber}
        `,
    };

    await chatBotService.callSendAPI(req.body.psid, response);

    return res.status(200).json({
      message: "ok",
    });
  } catch (e) {
    console.log("Error table reservation:", e);
    return res.status(500).json({ message: "Server Error" });
  }
};

export default {
  postWebhook,
  getWebhook,
  setupProfile,
  setupPersistentMenu,
  handleTableReservation,
  handlePostReserveTable,
};
